### PR TITLE
Mac/Intel assembly version

### PR DESCRIPTION
**Pull request by nakedmcse**
Here is the Mac/Intel assembly version

### CODE REVIEW

**Review by andrewhoyer — COMMENTED** [review]
This is really interesting code. A lot more verbose than other languages due to how granular each command is.

**Comment by andrewhoyer** [comment]
Walker, could you edit the main README file to include Assembly in the list of languages? I've been doing it in a few cases, but it would save me a step, and keep all updates per language within a group of commits.

**Comment by nakedmcse** [comment]
Sure - I'll do it after dinner.  I may cut the verbosity down too by doing a more general purpose print subroutine - a lot of the length of this is repeated very similar prints.

**Comment by andrewhoyer** [comment]
Thank you for this entry, and for your updated work. It's really great to have code like this in the project.

**Pull request merged**
