### PR TITLE
Added C# code for Leap Year

### LINKED ISSUE #13: Add language: C#
Please see [CONTRIBUTING.md](https://github.com/andrewhoyer/leap-year/blob/main/CONTRIBUTING.md) for details on how to create a good PR for this project.

If you are going to work on this, please add a comment to avoid duplication of work.

### PR DESCRIPTION
**Pull request by blindaks**
Closes #13

### CODE REVIEW

**Comment by andrewhoyer** [comment]
Can you make one addition to your PR? Please a link to your C# folder in the main README file of the repo. That way there's a link to it on the main page below the list of languages.

This is noted in the CONTRIBUTING file, but it's not totally clear, so I'm going to fix that part as well.

Please update the PR and I will review it again.

**Comment by blindaks** [comment]
Sure.

**Comment by andrewhoyer** [comment]
You got the C# folder in - great - but you changed every line in the file. This should be only a single added line. It looks like you changed * to - at the beginning of each line, which changes it from a bullet point list to a checkbox list. Revert back to * and that should be okay.

**Comment by andrewhoyer** [comment]
Thank you! I'm going to merge the C# solution into the repo. I've marked the PR as hacktoberfest-accepted so it should show up in Hacktoberfest for you.

**Comment by blindaks** [comment]
Thank you :)

**Pull request merged**
