### PR TITLE
Added MSSQL

### PR DESCRIPTION
**Pull request by rohitmore07**

### CODE REVIEW

**Comment by andrewhoyer** [comment]
You'll need a README.md in that folder (just like MySQL) and you need to edit the README.md in the root folder of the project.

Please read the CONTRIBUTING.md file carefully, which explains all of the required items. Once you've updated your code and pushed them to this PR, I'll review it.

Also, please update this PR, don't create a new one, so we can maintain the history of updates.

**Comment by rohitmore07** [comment]
I have added README.md in the folder. I would appreciate it if you could review and merge it when possible.

**Comment by rohitmore07** [comment]
@andrewhoyer Check Here https://github.com/rohitmore07/leap-year/branches

**Comment by andrewhoyer** [comment]
Hi @rohitmore07 You need to push all changes to this PR. There's nothing I can do by looking at your specific branches, and having multiple PRs makes things confusing. Many other contributions here have had one or more revisions, all on the same PR.

**Comment by rohitmore07** [comment]
Check once @andrewhoyer

**Pull request closed without merging**
