### PR TITLE
Added Leap year in Assembly using emu-8086

### PR DESCRIPTION
**Pull request by mehdi621-git**
Leap year is added in assembly emu-8086

### CODE REVIEW

**Comment by mehdi621-git** [comment]
Please merge this under HacktoberFest 2024

**Comment by andrewhoyer** [comment]
Hey @mehdi621-git. A couple of issues:

1. Your folder is named Aseembly-emu-8086, with Assembly spelled incorrectly.

2. Please edit the README.md file in the root folder to have an entry and a link to your folder. Include it in the list as "Assembly-emu-8086".

Add those changes to this PR and I will review it once again.

**Comment by mehdi621-git** [comment]
Corrected Assembly Spell and Added to Root .

**Review by andrewhoyer — APPROVED** [review]
Thanks, looks complete!

**Comment by andrewhoyer** [comment]
Hey @mehdi621-git, I have merged your PR and labelled it hacktoberfest-accepted.

**Pull request merged**
